FROM arm64v8/openjdk:11-jre

MAINTAINER tommylikehu@gmail.com

USER root

RUN apt update && \
    apt -y install curl && \
    apt -y install jq && \
    apt -y install xmlstarlet

COPY entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]
