apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-secrets
  namespace: repo
spec:
  name: website-secrets
  keysMap:
    server_crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    server_key:
      path: secrets/data/mindspore/website-secrets
      key: server.key
    rsyncd_secrets:
      path: secrets/data/mindspore/repo
      key: rsyncd.secrets
    auth_files:
      path: secrets/data/mindspore/repo
      key: auth_files

