# Config web service
---
apiVersion: v1
kind: Service
metadata:
  name: mailman-web-service
  namespace: mail
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: f3c0cba6-7b7b-4bb5-a1ee-4ea1e78ff214
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 159.138.132.224
  ports:
  - port: 8000
    name: website-port-uwsgi-http
    nodePort: 30059
    targetPort: 8000
    protocol: TCP  
  - port: 80
    name: website-port-http
    nodePort: 30061
    targetPort: 80
    protocol: TCP
  - port: 443
    name: website-port-https
    nodePort: 30062
    targetPort: 443
    protocol: TCP
  selector:
    component: mail-web-service
  type: LoadBalancer

# Deployment for mail web service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mailman-web
  namespace: mail
  labels:
    component: mail-web-service
    app: mail-suit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mail-web-service
      app: mail-suit-service
  template:
    metadata:
      labels:
        component: mail-web-service
        app: mail-suit-service
    spec:
      hostname: mailman-web
      containers:
        - name: mailman-web
          # We modified the mail-web image to add static folder.
          image: swr.cn-north-1.myhuaweicloud.com/openeuler/mail-web:v1.0.0
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman-web-config
              name: mailman-web-configmap-volume
            - mountPath: /etc/nginx/ssl
              name: mailman-secret-volume
            - mountPath: /opt/mailman-web-data
              name: mailman-web-volume
          env:
            - name: DATABASE_TYPE
              value: postgres
            - name: DATABASE_URL
              value: postgres://mailman:mailmanpass@mailman-database-0.mail-suit-service.mail.svc.cluster.local/mailmandb
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailsecret
                  key: HYPERKITTY_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailsecret
                  key: SECRET_KEY
            - name: UWSGI_STATIC_MAP
            # NOTE: This static folder has been added into docker image located at /opt/mailman-web/static
              value: /static=/opt/mailman-web-data/static
            - name: MAILMAN_REST_URL
              value: http://mailman-core-0.mail-suit-service.mail.svc.cluster.local:8001
            - name: MAILMAN_HOST_IP
              value: mailman-core-0.mail-suit-service.mail.svc.cluster.local
            - name: MAILMAN_ADMIN_USER
              value: openeuler
            - name: MAILMAN_ADMIN_EMAIL
              value: freesky.edward@gmail.com
            #NOTE: this is the domain name that mailman web will serve
            - name: SERVE_FROM_DOMAIN
              value: mailweb.openeuler.org
          #NOTE: Command is overwritten for the purpose of copy config file into dest folder
          command:
            - /bin/sh
            - -c
            - |
              cp /opt/mailman-web-config/settings_local.py /opt/mailman-web-data;
              docker-entrypoint.sh nginx && uwsgi --ini /opt/mailman-web/uwsgi.ini;
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
      volumes:
        - name: mailman-web-volume
          emptyDir: {}
        - name: mailman-web-configmap-volume
          configMap:
            name: mailman-web-configmap
        - name: mailman-secret-volume
          secret:
            secretName: mailcertsecret
