FROM tiangolo/uwsgi-nginx-flask:python3.7
MAINTAINER tommylike <tommylikehu@gmail.com>

RUN pip install Flask-BasicAuth && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
    chmod +x kubectl && \
    mv kubectl /usr/bin/

COPY ./app /app
