pipeline {
    agent { node { label 'website-sync' } }
    environment {
        GITEE_TOKEN = credentials('gitee_token_id')
    }
    stages {
        stage('source code clone') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[$class: 'LocalBranch'], [$class: 'RelativeTargetDirectory', relativeTargetDir: "${env.BUILD_NUMBER}/mindspore.github.io"]],
                    userRemoteConfigs: [[url: "https://mindspore_ci:${env.GITEE_TOKEN}@gitee.com/mindspore_ci/mindspore.github.io"]]
                ])
            }
        }
        stage('update website content') {
            steps {
                sh '''#!/bin/bash
                    cd ${WORKSPACE}/${BUILD_NUMBER}/mindspore.github.io/scripts
                    WORK_DIR=${WORKSPACE}/${BUILD_NUMBER} ./git_update_webapp_content.sh
                    cd ${WORKSPACE}/${BUILD_NUMBER}/mindspore.github.io
                    git config --global user.name mindspore-ci-bot
                    git config --global user.email tommylike@qq.com
                    git status
                    git add -A
                    git commit -m "Update website files generated by mindspore && docs repo"
                    if [ $? -eq 0 ];
                    then
                        echo "Starting to update remote codes."
                        git push https://mindspore_ci:${GITEE_TOKEN}@gitee.com/mindspore_ci/mindspore.github.io master
                    else
                        echo "nothing to commit or failed to commit change files"
                    fi
                   '''
            }
        }
    }

    post {
        success {
            echo 'succeeeded!'
        }

        failure {
            echo 'failed :('
        }
        always {
            sh '''#!/bin/bash
                    rm -rf ${WORKSPACE}/${BUILD_NUMBER}
                '''
        }
    }
}