# Resource for small specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: small-slaves-service
  namespace: jenkins
  labels:
    app: small-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: small-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: small-slaves
  namespace: jenkins
  labels:
    app: small-slaves
spec:
  serviceName: small-slaves-service
  replicas: 0
  selector:
    matchLabels:
      app: small-slaves
  template:
    metadata:
      labels:
        app: small-slaves
    spec:
      initContainers:
        - name: slave-init
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/jenkins-slave-tools:0.0.1
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mindspore-jenkins
                  key: jenkins-user-password
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://mindspore-jenkins.jenkins.svc.cluster.local:80
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: x86;k8s-small
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/ms_check_slave:0.0.2
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: small-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
            - mountPath: /home/jenkins/share-data
              name: jenkins-share-data
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 2000m
              memory: 3000Mi
          env:
            - name: JENKINS_TUNNEL
              value: mindspore-jenkins-agent:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://mindspore-jenkins.jenkins.svc.cluster.local:80
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
        - name: jenkins-share-data
          persistentVolumeClaim:
            # NOTE: this persistenvolumeclaim is imported on CCE web console, not created by command.
            claimName: cce-efs-import-k3paa03e-auh7
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: small-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 200Gi
        storageClassName: "sas"
