# Config web service
---
apiVersion: v1
kind: Service
metadata:
  name: mailman-web-service
  namespace: mail
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 8409ecd7-39d4-419a-84da-5c2a3d747915
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 49.4.27.171
  ports:
  - port: 8000
    name: website-port-uwsgi-http
    targetPort: 8000
    protocol: TCP  
  - port: 80
    name: website-port-http
    targetPort: 80
    protocol: TCP
  - port: 443
    name: website-port-https
    targetPort: 443
    protocol: TCP
  selector:
    component: mail-web-service
  type: LoadBalancer

# Deployment for mail web service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mailman-web
  namespace: mail
  labels:
    component: mail-web-service
    app: mail-suit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mail-web-service
      app: mail-suit-service
  template:
    metadata:
      labels:
        component: mail-web-service
        app: mail-suit-service
    spec:
      hostname: mailman-web
      containers:
        - name: mailman-web
          # We modified the mail-web image to add static folder.
          image: mindspore/mail-web:v1.0.1
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman-web-config
              name: mailman-web-configmap-volume
            - name: mailman-cert-secrets
              mountPath: /etc/nginx/ssl/server.crt
              subPath: server_crt
            - name: mailman-cert-secrets
              mountPath: /etc/nginx/ssl/server.key
              subPath: server_key
            - mountPath: /opt/mailman-web-data
              name: mailman-web-volume
            - mountPath: /usr/lib/python3.6/site-packages/postorius/templates/postorius/lists/summary.html
              name: mailman-webpage-hack-volume
              subPath: summary.html
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: postgres_password
            - name: DATABASE_TYPE
              value: postgres
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: hyperkitty_api_key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: secret_key
            - name: UWSGI_STATIC_MAP
            # NOTE: This static folder has been added into docker image located at /opt/mailman-web/static
              value: /static=/opt/mailman-web-data/static
            - name: MAILMAN_REST_URL
              value: http://mailman-core-0.mail-suit-service.mail.svc.cluster.local:8001
            - name: MAILMAN_HOST_IP
              value: mailman-core-0.mail-suit-service.mail.svc.cluster.local
            - name: MAILMAN_ADMIN_USER
              value: mindspore
            - name: MAILMAN_REST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_user
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_password
            - name: MAILMAN_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_admin_email
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_username
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_password
            #NOTE: this is the domain name that mailman web will serve
            - name: SERVE_FROM_DOMAIN
              value: mailweb.mindspore.cn
          #NOTE: Command is overwritten for the purpose of copy config file into dest folder
          command:
            - /bin/sh
            - -c
            - |
              export DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mailman-database-0.mail-suit-service.mail.svc.cluster.local/mailmandb
              pip install hyperkitty==1.3.2;
              cp /opt/mailman-web-config/settings_local.py /opt/mailman-web-data;
              docker-entrypoint.sh nginx && uwsgi --ini /opt/mailman-web/uwsgi.ini;
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
      volumes:
        - name: mailman-web-volume
          emptyDir: {}
        - name: mailman-web-configmap-volume
          configMap:
            name: mailman-web-configmap
        - name: mailman-cert-secrets
          secret:
            secretName: mailman-cert-secrets
        - name: mailman-webpage-hack-volume
          configMap:
            name: mailman-webpage-hack
